version: '3'
services:

    telegram:
      build:
        context: ./
        dockerfile: ./Dockerfile
      user: "node"
      environment:
        - NODE_ENV=production
      volumes:
        - ./src:/home/node/app/src
      expose:
        - "8082"
      ports:
        - 8082:8082
      command: "npm start"